# Site wide configuration

title:            Paul Biggins
locale:           en_US
url:              #www.paulbiggins.com


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Paul Biggins
  avatar: bio-photo.jpg
  bio: "I'm an Antenna Design Engineer on weekdays, a Dabler on weekends, and an Adventurer all the time."
  email: paul@paulbiggins.com
  disqus-shortname: 
  twitter: pbiggins
  facebook: #username
  google:
    plus: PaulBigginsMinus
    analytics: #https://support.google.com/webmasters/answer/35179?hl=en
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: paulbiggins
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: pbiggins
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: pasque_
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
